
INPUT_DATA = "/ei/projects/c/c3109f4b-0db1-43ec-8cb5-df48d8ea89d0/scratch/repos/CAGE/input_data"
INTERMEDIATE_DATA = "/ei/projects/c/c3109f4b-0db1-43ec-8cb5-df48d8ea89d0/scratch/repos/CAGE/intermediate_data/snakemake_intermediate_data"

rule make_up_results:
	output: "the_results.txt"
	shell: r"sleep 1m; touch the_results.txt"

rule trying_hisat_2:
	output: "hisat_results.txt"
	shell: r"""source package f9c1e0c5-d0e8-4ba0-9edd-88235400fa13 
		   hisat2 --help > hisat_results.txt"""


rule trim_reads:
    output: 
        trimmed = "{INTERMEDIATE_DATA}/{sample}_trimmed.fastq.gz"
    input: 
        read_1 = expand("{file}/cage_data/Fastq_R1/{sample}_R1.fastq.gz", file = INPUT_DATA),
        read_2 = expand("{file}/cage_data/Fastq_R2/{sample}_R2.fastq.gz", file = INPUT_DATA),
        solexa = expand("{file}/solexa_sequencing_primers.fa", file = INPUT_DATA),

    log: "{INTERMEDIATE_DATA}/{sample}_trim_reads.log"
    shell: 
        r"""
        source package 50fcf79b-73a3-4f94-9553-5ed917823423
        trimmomatic PE -threads 16  {input.read_1} {input.read_2} -baseout {output.trimmed} ILLUMINACLIP:../solexa_sequencing_primers.fa:2:30:12 SLIDINGWINDOW:4:20 MINLEN:20 AVGQUAL:20 
        """




