from snakemake.utils import min_version

min_version("7.20")

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/trim.smk"
include: "rules/align.smk"
include: "rules/post_align.smk"
include: "rules/r_analysis.smk"
include: "rules/circos.smk"

